language: common-lisp

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
#    - LISP=cmucl # /home/travis/.cim/bin/cl: 4: .: Can't open /home/travis/.cim/config/current.3271
    - LISP=ecl

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

script:
  - cl -e '(in-package :cl-user)'
       -e '(ql:quickload :check-it)'
       -e '(ql:quickload :check-it-test)'
       -e '(let ((*debugger-hook*
                  (lambda (c h)
                    (declare (ignore h))
                    (print c t)
                    (uiop:quit -1))))
             (check-it-test:test-all))'
