language: common-lisp

sudo: required
env:
  matrix:
    - LISP=abcl
#    - LISP=allegro # problems loading Quicklisp as of 4/22/15
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
#    - LISP=cmucl # /home/travis/.cim/bin/cl: 4: .: Can't open /home/travis/.cim/config/current.3271
    - LISP=ecl

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

script:
  - cl -e '(in-package :cl-user)'
       -e '(ql:quickload :check-it)'
       -e '(ql:quickload :check-it-test)'
       -e '(check-it-test::run-tests-for-travis)'
